### ISSUE TITLE
[Bug/Help] portal: 应用配置HTML表单default选项未生效

### ISSUE THREAD

**Issue by Cloudac7** [PKUHPC/OpenSCOW#1462]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

按照官方文档[配置HTML表单: 配置解释](https://pkuhpc.github.io/OpenSCOW/docs/deploy/config/portal/apps/configure-attributes#%E9%85%8D%E7%BD%AE%E8%A7%A3%E9%87%8A)的说明，可以为自定义表单项 `attributes` 添加 `default` 设置来为该表单项添加一个默认值。

但当应用了如下的设置后，访问交互式作业应用提交页面时，未能正确加载设定的默认值，且切换未曾使用过的新用户、注释掉 `placeholder` 均未起效。因此推测为BUG。

```yaml
attributes:
  - type: text
    name: textModuleName
    label: Modules
    required: false  # 输入需要额外加载的环境模块列表
    placeholder: 输入需要额外加载的环境模块列表，模块之间用空格分开（比如：deepmd/2.2.7 cuda/11.8）  # 提示信息
    default: miniconda/3
  - type: text
    name: textCondaName
    label: conda环境
    required: false  # 输入运行Jupyter的conda环境，默认使用base环境
    placeholder: 输入conda虚拟环境名称  # 提示信息
    default: base
  - type: text
    name: sbatchOptions
    label: 其他sbatch参数
    required: false
    placeholder: "比如：--gpus=gres:1 --mem=16G"
```

截图（已注释掉 `placeholder`）如下：

![image](https://github.com/user-attachments/assets/74a348d0-ecc5-4648-83de-3c90079715a3)

### 期望结果 | What did you expect to happen

可以正确应用默认值设置

### 复现方法 | Steps To Reproduce

1. 添加自定义表单项并设置默认值
2. 访问交互式应用列表，选择添加了自定义表单项的应用，点击进入

### 运行环境 | Environment

```Markdown
- OS: KOS 5.8
- Scheduler: Slurm 21.08.8
- Docker: 26.1.3
- Docker-compose: 26.1.3
- SCOW cli: 1.6.3
- SCOW: 1.6.3
- Adapter: 1.6.0
```
